name: zombie_conga_flame
description: This is a Flutter version of the Zombie Conga app from the _2D Apple Games by Tutorials Ed 3.0_ book published by Kodeco, formerly raywenderlich.com.  It was created using Very Good Ventures[Flame game template](https://verygood.ventures/dev/tools) very_good create flame_game.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  audioplayers: ^6.2.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  flame: ^1.16.0
  flame_audio: ^2.1.8
  flame_behaviors: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  window_manager: ^0.4.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^10.0.0
  flame_test: ^1.17.4
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
    - assets/fonts/
